name: Docker Image CI

on:
  workflow_dispatch: { }
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-binary:
    uses: ./.github/workflows/go.yml

  build:
    needs: [ go-binary ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@main
        with:
          name: binary
          path: bin/admission-cert-init

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
