name: Go

on:
  workflow_call: { }
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get
        run: go get ./main
      - name: Build
        run: CGO_ENABLED=0 go build -o bin/cronjob-pod-cleaner ./main

      - uses: actions/upload-artifact@main
        with:
          name: binary
          path: bin/cronjob-pod-cleaner